# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My blog
email: chaichuan@139.com
description: > # this means to ignore newlines until "baseurl:"
  A great man once said it is necessary to dill as much as possible, and the more you apply it in real situations, the more natural it will become. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.chaichuan.net" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  chaichuan

# Build settings
markdown: kramdown
encoding: utf-8